services:
  mav-scrap:
    image: denoland/deno:2.3.6
    container_name: mav-scrap
    volumes:
      - ./app:/app
    working_dir: /app
    command: deno run --allow-net --allow-env --watch main.ts
    environment:
      - TOR_PROXY_URL=socks5h://tor-proxy:9050
    networks:
      - tor-proxy-network

networks:
  tor-proxy-network:
    external: true

